### ISSUE TITLE
Code doesn't currently work

### ISSUE THREAD

**Issue by NoorMkdad** [NoorMkdad/GDRandomizer#2]
What the title says, I am having issues w/ the string substitution

**Comment by MellyTheFireyMelly** [comment]
ok

**Comment by MellyTheFireyMelly** [comment]
What do you mean by "string substitution" I don't see anything wrong with the code?

**Comment by NoorMkdad** [comment]
you replace an item in a string and replace it with a variable

**Comment by NoorMkdad** [comment]
you should know this

**Comment by NoorMkdad** [comment]
I also used the wrong ver of string substitution formatting, used python 2.x rather than the 3.x syntax
